version: 0.1

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Update AWS CLI to the latest version
      - pip install --upgrade awscli